server:
  port: 6001

spring:
  application:
    name: gateway-server
  redis:
    host: localhost
    port: 6379
    password:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: espresso-auth
          uri: lb://auth-server
          predicates:
            - Path=/auth/**
        - id: espresso-menu
          uri: lb://menu-server
          predicates:
            - Path=/menu/**