server:
  port: 8011
  servlet:
    context-path: /menu

spring:
  application:
    name: menu-server
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    host: localhost
    port: 6379
    password: