server:
  port: 8080
  servlet:
    context-path: /auth
spring:
  application:
    name: auth-server
  redis:
    host: espresso-cache.3bsogg.ng.0001.use1.cache.amazonaws.com
    port: 6379
    password:
  datasource:
    username: admin
    password: nusiss666
    url: jdbc:mysql://database-1.ct5asudpymeo.us-east-1.rds.amazonaws.com:3306/espresso?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 820446727245-j0863bgvsc1bke4vtkh78op8mci55vln.apps.googleusercontent.com
            client-secret: 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
            redirectUri: "http://espresso-auth.hexpanda.click/auth/public/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

app:
  tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
  tokenExpirationMsec: 864000000
  authorizedRedirectUris:
    - https://espresso.malcolmpro.com/#/